# Generated by Django 3.2.9 on 2021-12-02 14:39

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211129_1802'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('kind', models.CharField(choices=[('cat', 'Dog'), ('dog', 'Cat')], max_length=3)),
                ('file_type', models.CharField(choices=[('png', 'PNG'), ('gif', 'GIF'), ('jpg', 'JPG'), ('jpeg', 'JPEG')], max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
