# Generated by Django 3.2.9 on 2021-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211202_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='url',
            field=models.TextField(),
        ),
    ]
